material: waxed_chiseled_copper
cost: 22
unlocked:
- pylonbase:hydraulic_grindstone_turner
- pylonbase:hydraulic_mixing_attachment
- pylonbase:hydraulic_press_piston
- pylonbase:hydraulic_hammer_head
- pylonbase:hydraulic_pipe_bender
- pylonbase:hydraulic_table_saw
- pylonbase:hydraulic_excavator
- pylonbase:hydraulic_farmer
